Espanol
janos-ijgyarto/HuxQt pull request #2
Opened 2023-05-16 18:34 UTC by exequielpagliari

Hello!

How are you?

I have translated Read.me into Spanish, it is at the bottom of it.

I just need to understand how the Links of the titles work for the references of each one and it would be fully functional.

Thanks for the software, I needed it.

2025-05-09 23:45 UTC, janos-ijgyarto commented
Hey there, sorry for getting back to you this late, Github never notified me about this.

I'm more than happy to add a translation, though it may be out of date. Can we discuss it in DMs?

2025-05-10 00:12 UTC, exequielpagliari commented
Hello!

Thank for reply!

No problem with talk on DM.

2025-05-23 00:35 UTC, janos-ijgyarto requested changes

2025-05-23 00:35 UTC, janos-ijgyarto commented on readme/spanish.md
Looks good, but you will need to adjust the markdown links to the headings, since the headings were also translated. I will highlight an example

2025-05-23 00:35 UTC, janos-ijgyarto commented on readme/spanish.md
> +Una vez que abra Hux, primero debes [importar](#importing-scenarios) un escenario desde la carpeta dividida (split folder), or [abrir](#loading-scenarios) un archivo de escenario Hux.
This is an example, you need to change `#importing-scenarios` to match the translated heading (this will allow users to click the link and be taken to the corresponding part of the document)

2025-05-23 00:36 UTC, janos-ijgyarto commented on readme.md
Since the Readme is now in separate files, the one at the root could be trimmed back to just the short summary, followed by links to the specific translations

2025-10-02 17:39 UTC, exequielpagliari commented
Ey, @janos-ijgyarto, y repair the spanish links on Spanish.md

2025-10-02 17:56 UTC, janos-ijgyarto requested changes

2025-10-02 17:56 UTC, janos-ijgyarto commented on readme/spanish.md
> +Una vez que abra Hux, primero debes [importar](#importando-escenarios) un escenario desde la carpeta dividida (split folder), or [abrir](#loading-scenarios) un archivo de escenario Hux.
The `abrir` is still using the english link

2025-10-02 17:56 UTC, janos-ijgyarto commented on readme/spanish.md
> +Cuando hace click en una terminal en el [Navegador de Escenarios](#navegador-de-escenarios), se abre una ventana del [Editor de Terminal](#terminal-editor) para este terminal.
`Editor de Terminal` also needs to be updated

2025-10-02 19:37 UTC, janos-ijgyarto approved these changes

2025-10-02 19:38 UTC, merged